"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _profile_page from './profile-page.bones.json'

registerBones({
  "profile-page": _profile_page,
})
