/* Auto-generated by scripts/sync-app-version.mjs — do not edit manually. */
export const APP_VERSION = "1.1.0";
export const API_VERSION = "1";
export const BUILD_ID = "2026-07-08T12:59:50.203Z";
export const MIN_CLIENT_VERSION = "1.0.0";
export const SERVICE_NAME = "fixoindia";

export const getVersionPayload = () => ({
  appVersion: APP_VERSION,
  apiVersion: API_VERSION,
  buildId: BUILD_ID,
  minClientVersion: MIN_CLIENT_VERSION,
  service: SERVICE_NAME
});
